# Generated by Django 2.0.2 on 2018-03-30 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File_invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, help_text='Дата загрузки банковской выписки в систему. Только для чтнеия.', verbose_name='Дата загрузки выписки')),
                ('number_invoice', models.IntegerField(help_text='Порядковый номер выписки.', verbose_name='Номер выписки')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, help_text='Дата загрузки платежа в систему. Только для чтнеия.', verbose_name='Дата загрузки платежа')),
                ('last_change_date', models.DateField(auto_now=True, help_text='Дата последнего измнения атрибутов платежа.', verbose_name='Дата изменения атрибудтов платежа')),
                ('payment_date', models.DateField(help_text='Дата совершения платежа.', verbose_name='Дата совершения платежа')),
                ('client_full_name', models.CharField(help_text='Полное имя плательщика.', max_length=250, verbose_name='ФИО плательщика')),
                ('account_id', models.IntegerField(help_text='Номер счета клиента (ID счета) в UTM5.', verbose_name='Номер счета')),
                ('client_address', models.CharField(help_text='Полный адрес плательщика.', max_length=300, verbose_name='Адрес плательщика')),
                ('bank_id', models.CharField(help_text='Краткий идентификатор банка.', max_length=25, verbose_name='Признак банка')),
                ('internet_payment', models.DecimalField(decimal_places=2, help_text='Сумма платежа за услуги Интернет.', max_digits=6, verbose_name='Абонентская плата Интернет')),
                ('monthly_phone_payment', models.DecimalField(decimal_places=2, help_text='Сумма платежа за услуги Местной теелфонной связи.', max_digits=6, verbose_name='Аблннентская плата МТС')),
                ('mg_mn_payment', models.DecimalField(decimal_places=2, help_text='Сумма платежа за услуги Междугородней/Международной связи.', max_digits=6, verbose_name='Платеж за МГ/МН')),
                ('unknown_payment', models.DecimalField(decimal_places=2, help_text='Сумма платежа, который невозможно идентифицировать по категориям.', max_digits=6, verbose_name='Неизвестный платеж')),
                ('is_complited', models.BooleanField(help_text='Позволяет понять был ли отправлен (проведен) платеж на сервер.', verbose_name='Платеж обработан')),
                ('in_invoice', models.ForeignKey(help_text='Выписка6 в которой фигурировал данный платеж.', on_delete=django.db.models.deletion.CASCADE, to='upayment.Invoice', verbose_name='Выписка')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
