# Generated by Django 2.0.2 on 2018-04-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='name_invoice',
            field=models.CharField(default='Выписка № <django.db.models.fields.IntegerField> от <django.db.models.fields.DateField>', max_length=100),
        ),
    ]
