# Generated by Django 2.0.2 on 2018-04-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0003_auto_20180416_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='name_invoice',
            field=models.CharField(help_text='Наименование выписки. Поле не требует редактирования и вычисляется автоматически.', max_length=100, null=True, verbose_name='Наименование выписки'),
        ),
    ]
