# Generated by Django 2.0.2 on 2018-04-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0004_auto_20180416_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='name_invoice',
            field=models.CharField(blank=True, default='', help_text='Наименование выписки. Поле не требует редактирования и вычисляется автоматически.', max_length=100, verbose_name='Наименование выписки'),
        ),
    ]
