# Generated by Django 2.0.2 on 2018-05-18 09:35

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0005_auto_20180416_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total',
            field=computed_property.fields.ComputedDecimalField(compute_from='calc_total', decimal_places=2, default=0.0, editable=False, max_digits=6),
        ),
    ]
