# Generated by Django 2.0.2 on 2018-05-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0007_auto_20180518_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Позволяет понять проведены ли платежи по выписке. И была ли подтверждена обработка.', verbose_name='Выписка обработана и проведена'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name_invoice',
            field=models.CharField(blank=True, default='Без имени', help_text='Наименование выписки. Поле не требует редактирования и вычисляется автоматически.', max_length=100, verbose_name='Наименование выписки'),
        ),
    ]
