# Generated by Django 2.0.2 on 2018-05-25 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0008_auto_20180523_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='creation_date',
            field=models.DateField(auto_now_add=True, help_text='Дата формирования отчета. Только для чтения', null=True, verbose_name='Дата формирования отчета'),
        ),
        migrations.AddField(
            model_name='report',
            name='equip_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма платежей по выписке за приобретение оборудования.', max_digits=6, verbose_name='Приобретение оборудования'),
        ),
        migrations.AddField(
            model_name='report',
            name='in_invoice',
            field=models.ForeignKey(help_text='Выписка, по которой сформирован отчет.', null=True, on_delete=django.db.models.deletion.CASCADE, to='upayment.Invoice', verbose_name='Выписка'),
        ),
        migrations.AddField(
            model_name='report',
            name='internet_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма платежей по выписке за услуги Интернет.', max_digits=6, verbose_name='Абонентская плата Интернет'),
        ),
        migrations.AddField(
            model_name='report',
            name='mg_mn_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма платежей по выписке за услуги Междугородней/Международной связи.', max_digits=6, verbose_name='Платежи за МГ/МН'),
        ),
        migrations.AddField(
            model_name='report',
            name='monthly_phone_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма платежей по выписке за услуги Местной теелфонной связи.', max_digits=6, verbose_name='Аблннентская плата МТС'),
        ),
        migrations.AddField(
            model_name='report',
            name='name_report',
            field=models.CharField(blank=True, default='Без имени', help_text='Наименование отчета и его файла. Поле не требует редактирования и вычисляется автоматически в представлении.', max_length=100, verbose_name='Наименование отчета'),
        ),
        migrations.AddField(
            model_name='report',
            name='number_report',
            field=models.IntegerField(default=0, help_text='Порядковый номер отчета.', verbose_name='Номер отчета'),
        ),
        migrations.AddField(
            model_name='report',
            name='operator',
            field=models.CharField(default='Администратор', help_text='Оператор, сформировавшиий отчет.', max_length=100, verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='report',
            name='phone_install_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма платежей по выписке за услугу установки телефоноа.', max_digits=6, verbose_name='Установка телефона'),
        ),
        migrations.AddField(
            model_name='report',
            name='phone_reinstall_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма платежей по выписке за услугу переустановки телефоноа.', max_digits=6, verbose_name='Переустановка телефона'),
        ),
        migrations.AddField(
            model_name='report',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Общая сумма платежей по выписке.', max_digits=6, verbose_name='Итого'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name_invoice',
            field=models.CharField(blank=True, default='Без имени', help_text='Наименование выписки. Поле не требует редактирования и вычисляется автоматически в представлении.', max_length=100, verbose_name='Наименование выписки'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Общая сумма платежей по всем услугам.', max_digits=6, verbose_name='Итого'),
        ),
    ]
