# Generated by Django 2.0.2 on 2018-05-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0009_auto_20180525_0905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File_invoice',
        ),
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, default=None, help_text='Файл отчета, доступный для скачивания и экспорта.', upload_to='reports/', verbose_name='Файл отчета'),
        ),
    ]
