# Generated by Django 2.0.2 on 2018-05-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0010_auto_20180525_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_waiting',
            field=models.BooleanField(default=False, help_text='Позволяет определить, что выписка обработана оператором. И готова к обработке.', verbose_name='Выписка ожидает отправки на сервер'),
        ),
    ]
