# Generated by Django 2.0.2 on 2018-05-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0012_auto_20180529_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='equip_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма платежа, за приобретенное оборудование.', max_digits=6, verbose_name='Платеж за оборудование'),
        ),
        migrations.AddField(
            model_name='payment',
            name='other_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма платежа, за услуги, не подходящих под остальные категории.', max_digits=6, verbose_name='Остальные платежи'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reinstall_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма платежа, за услуги переустановки телефона.', max_digits=6, verbose_name='Платеж переустановка'),
        ),
    ]
