# Generated by Django 2.0.2 on 2018-05-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0013_auto_20180529_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='equip_payments',
            new_name='equip_payment',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='other_payments',
            new_name='other_payment',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='reinstall_payments',
            new_name='reinstall_payment',
        ),
    ]
