# Generated by Django 2.0.2 on 2018-05-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0014_auto_20180530_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bank_id',
            field=models.CharField(default='Неизвестен', help_text='Идентифицирует принадлежность выписки к банку (СБР, ВЗР).', max_length=10, verbose_name='Идентификатор банка'),
        ),
    ]
