# Generated by Django 2.0.2 on 2018-05-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0015_auto_20180530_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_comment',
            field=models.CharField(default='-', help_text='Банковский комментарий к платежу, взятый из выписки.', max_length=100, verbose_name='Комментарий банка'),
        ),
    ]
