# Generated by Django 2.0.2 on 2018-05-30 09:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0016_payment_bank_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='internet_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Сумма платежа за услуги Интернет.', max_digits=6, verbose_name='Абонентская плата Интернет'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mg_mn_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Сумма платежа за услуги Междугородней/Международной связи.', max_digits=6, verbose_name='Платеж за МГ/МН'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='monthly_phone_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Сумма платежа за услуги Местной теелфонной связи.', max_digits=6, verbose_name='Аблннентская плата МТС'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='unknown_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Сумма платежа, который невозможно идентифицировать по категориям.', max_digits=6, verbose_name='Неизвестный платеж'),
        ),
    ]
