# Generated by Django 2.0.2 on 2018-05-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0017_auto_20180530_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account_id',
            field=models.CharField(default='0000', help_text='Номер счета клиента (ID счета) в UTM5.', max_length=4, verbose_name='Номер счета'),
        ),
    ]
