# Generated by Django 2.0.2 on 2018-06-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0020_auto_20180531_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection_to_UTM_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(default='172.0.0.1', help_text='IP адрес сервера.', verbose_name='IP сервера')),
                ('user', models.CharField(default='Admin', help_text='Имя пользователя.', max_length=50, verbose_name='Пользователь')),
                ('password', models.CharField(default='', help_text='Пароль. Не более 50 символов.', max_length=50, verbose_name='Пароль')),
                ('transport_port', models.PositiveSmallIntegerField(default=22, help_text='Порт для подключения для установления соединения с сервером.', verbose_name='Номер порта для подключения')),
                ('remote_port', models.PositiveSmallIntegerField(default=3306, help_text='порт: который необходимо пробросить через тоннель.', verbose_name='Порт для БД')),
                ('database_user', models.CharField(default='Admin', help_text='Имя пользователя для подключения к БД.', max_length=50, verbose_name='Пользователь БД')),
                ('database_password', models.CharField(default='', help_text='Пароль для подключения к БД. Не более 50 символов.', max_length=50, verbose_name='Пароль БД')),
                ('database_name', models.CharField(default='UTM5', help_text='Наименование БД.', max_length=50, verbose_name='Имя БД')),
                ('database_host', models.GenericIPAddressField(default='172.0.0.1', help_text='IP адрес хоста с БД.', verbose_name='IP хоста с БД')),
                ('utm_util_path', models.CharField(default='', help_text='Полный путь к UTM5 утилите для запуска автоплатежей.', max_length=300, verbose_name='Путь к UTM5 payment утилите')),
                ('comment', models.CharField(default='Отсутствует', help_text='Подбробный комментарий', max_length=100, verbose_name='Комментарий')),
            ],
        ),
    ]
