# Generated by Django 2.0.2 on 2018-06-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0021_connection_to_utm_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='account_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='account_id_internet',
            field=models.CharField(default='Не определен', help_text='Номер счета клиента (ID счета) за услуги Интернет в UTM5.', max_length=4, verbose_name='Номер счета Интернет'),
        ),
        migrations.AddField(
            model_name='payment',
            name='account_id_phone',
            field=models.CharField(default='Не определен', help_text='Номер счета клиента (ID счета) за услуги Телефонии в UTM5.', max_length=4, verbose_name='Номер счета Телефония'),
        ),
        migrations.AlterField(
            model_name='connection_to_utm_settings',
            name='utm_util_path',
            field=models.CharField(default='', help_text='Полный путь к UTM5 утилите для запуска автоплатежей.', max_length=100, verbose_name='Путь к UTM5 payment утилите'),
        ),
    ]
