# Generated by Django 2.0.2 on 2018-06-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0022_auto_20180605_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_loaded',
            field=models.BooleanField(default=False, help_text='Позволяет определить, что выписка была загружена на сервер. И готова к редактированию.', verbose_name='Выписка загружена на сервер'),
        ),
    ]
