# Generated by Django 2.0.2 on 2018-07-05 08:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0023_invoice_is_loaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='Дата совершения платежа.', null=True, verbose_name='Дата совершения платежа')),
                ('client_full_name', models.CharField(help_text='Полное имя плательщика.', max_length=250, verbose_name='ФИО плательщика')),
                ('account_id', models.CharField(default='НЗВ', help_text='Номер счета клиента (ID счета) в UTM5.', max_length=4, verbose_name='Номер счета')),
                ('bank_comment', models.CharField(default='-', help_text='Банковский комментарий к платежу, взятый из выписки.', max_length=100, verbose_name='Комментарий банка')),
                ('summ', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Сумма платежа за услуги связи.', max_digits=6, verbose_name='Сумма платежа')),
                ('pyament_type', models.CharField(default='НЗВ', help_text='Тип платежа. Должен сопоставляться с лицевым счетом клиента.', max_length=10, verbose_name='Тип платежа')),
                ('payment_comment', models.CharField(default='нзв', help_text='Комментарий, необходимый для идентификации типа платежа в UTM5.', max_length=10, verbose_name='Комментарий к платежу')),
                ('payment_status', models.CharField(default='ИГН', help_text='Статус платежа. Служит для установления успешности выполнения опреации в UTM5.', max_length=10, verbose_name='Статус платежа')),
            ],
        ),
    ]
