# Generated by Django 2.0.2 on 2018-07-05 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0024_logpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpayment',
            name='in_invoice',
            field=models.ForeignKey(default=None, help_text='Выписка, в которой фигурировал данный платеж.', on_delete=django.db.models.deletion.CASCADE, to='upayment.Invoice', verbose_name='Выписка'),
        ),
    ]
