# Generated by Django 2.0.2 on 2018-07-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0025_logpayment_in_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpayment',
            name='client_address',
            field=models.CharField(default='', help_text='Полный адрес плательщика.', max_length=300, verbose_name='Адрес плательщика'),
        ),
    ]
