# Generated by Django 2.0.2 on 2018-07-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0026_logpayment_client_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='number_invoice',
        ),
    ]
