# Generated by Django 2.0.2 on 2018-07-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0027_remove_invoice_number_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(help_text='Дата совершения платежа.', verbose_name='Дата совершения платежа'),
        ),
    ]
