# Generated by Django 2.0.2 on 2018-08-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0028_auto_20180731_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='equip_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма платежей, за приобретенное оборудование.', max_digits=12, verbose_name='Платежи оборудования'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='internet_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма платежей за услуги Интернет.', max_digits=12, verbose_name='Абонентская плата Интернет'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='mg_mn_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма платежей за услуги Междугородней/Международной связи.', max_digits=12, verbose_name='Платежи за МГ/МН'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='monthly_phone_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма платежей за услуги Местной теелфонной связи.', max_digits=12, verbose_name='Аблннентская плата МТС'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='other_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма платежей, не подходящих под остальные категории.', max_digits=12, verbose_name='Остальные платежи'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reinstall_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Сумма платежей, за услуги переустановки телефона.', max_digits=12, verbose_name='Платежи переустановка'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Общая сумма всех платежей по выписке.', max_digits=12, verbose_name='Итого'),
        ),
    ]
