# Generated by Django 2.0.2 on 2018-08-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0029_auto_20180816_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBRParserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(default='Профиль 0', help_text='Название для данного профиля', max_length=30, verbose_name='Название профиля')),
                ('delimeter', models.CharField(default=';', help_text='Разделитель полей в файле банковской выписки', max_length=1, verbose_name='Разделитель')),
                ('date_position', models.PositiveIntegerField(default=0, help_text='Указание позиции, на которой следует искать дату платежа', verbose_name='Позиция с описанием даты платежа')),
                ('time_position', models.PositiveIntegerField(default=1, help_text='Указание позиции, на которой следует искать время платежа', verbose_name='Позиция с описанием времени платежа')),
                ('name_position', models.PositiveIntegerField(default=2, help_text='Указание позиции, на которой следует ФИО влиента', verbose_name='Позиция с описанием имени оплатишего клиента')),
                ('address_position', models.PositiveIntegerField(default=3, help_text='Указание позиции, на которой следует адрес клиента', verbose_name='Позиция с описанием адреса клиента')),
                ('comment_position', models.PositiveIntegerField(default=4, help_text='Указание позиции, на которой следует искать комментарий оператора банка', verbose_name='Позиция с описанием комментария к платежу')),
                ('summ_position', models.PositiveIntegerField(default=5, help_text='Указание позиции, на которой следует искать сумму платежа', verbose_name='Позиция с описанием суммы платежа')),
            ],
        ),
    ]
