# Generated by Django 2.0.2 on 2018-08-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upayment', '0030_sbrparserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbrparserprofile',
            name='example',
            field=models.CharField(default='01-08-2018;09-55-48;9040;9900000V;300445142394;ФИО;МО, г. Рошаль, ул. Косякова 13;Интернет;980,00;970,20;9,80;', help_text='Пример строки, который показывает как может выглядеть формат банковской выписки', max_length=300, verbose_name='Пример'),
        ),
    ]
